stages:
- name: build
  steps:
  - runScriptConfig:
      image: golang:latest
      shellScript: |-
        cat << EOF > hello.go
        package main
        import "fmt"
        func main() {
          fmt.Println("hello world")
        }
        CGO_ENABLED=0 go build hello.go
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: zerchin/test-pipeline:v1.0
      pushRemote: true
      registry: index.docker.io
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
