apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-test
  labels:
    app: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: zerchin/test-pipeline:v1.0
